### ISSUE TITLE
how to make column Uneditable

### ISSUE THREAD

**Issue by b805rohit** [mengshukeji/luckysheet-vue#1]
is there any way to make first column uneditable

**Comment by mengshukeji** [comment]
Now, we can use protection feature.

![image](https://user-images.githubusercontent.com/61444807/99659730-4375f200-2a9c-11eb-8123-a40ac37cb6c1.png)

Steps:
1. Select all the cells from column B to the last column, right-click the menu setting: cell format config, and remove the locked check box
2. Click the worksheet protection button in the toolbar and check the entire worksheet protection
