### ISSUE TITLE
只能用列数据画图吗？希望行也可以。

### ISSUE THREAD

**Issue by jzp1981** [mengshukeji/luckysheet-vue#4]

**Comment by Dushusir** [comment]
图表可以使用转置功能来交换行列数据，请尝试下。又任何疑问，请到 [Luckysheet issues](https://github.com/mengshukeji/Luckysheet/issues) 反馈
![image](https://user-images.githubusercontent.com/26371161/102969813-54999f00-4531-11eb-8bcf-9b634716bd24.png)
